### ISSUE TITLE
Tidak bisa menampilkan semua foto yang ada di account

### ISSUE THREAD

**Issue by muhghazaliakbar** [julles/laravel-instagram#1]
Makasih banyak gan atas packagenya, sangat membantu sekali. tetapi pada saat menampilkan foto menggunakan `IG::standardResolution()` fotonya ga tampil semua , cuma beberapa saja yang ditampilkan.

**Comment by julles** [comment]
oke gan di cek dulu yak

**Comment by julles** [comment]
Kayak nya instagram ga ngasih API buat ngambil semua gambar
solusi nya ane modif dikit di helper standardResolution() 
jadi bisa nambahin jumlah gambar yang di inginkan
Example
`IG::standardResolution(10)`  menampilkan 10 gambar 
`IG::standardResolution(50)`  menampilkan 50 gambar

> jangan lupa update dependencies nya 
> `composer update muhamadrezaar/instagram`

**Comment by muhghazaliakbar** [comment]
saya coba set count=100 tapi cuma tampil 42 foto. padahal fotonya ada 87.
